[package]
name = "spider-lib"
version = "1.1.0"
edition = "2024"
authors = ["mzyui <mzyui@proton.me>"]
description = "A Rust-based web scraping framework inspired by Scrapy (Python)."
homepage = "https://github.com/spider-lib/spider-lib"
repository = "https://github.com/spider-lib/spider-lib"
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/spider-lib"
keywords = ["web-scraping", "crawler", "scraper", "async", "rust"]
categories = ["web-programming", "development-tools", "parsing"]

[workspace]
members = [
    "spider-core",
    "spider-downloader",
    "spider-macro",
    "spider-middleware",
    "spider-pipeline",
    "spider-util",
]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

spider-util = "0.1.1"
spider-macro = "0.1.3"
spider-downloader = "0.1.2"
spider-middleware = "0.1.2"
spider-core = "0.1.1"
spider-pipeline = "0.1.3"

[dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

